/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThreatsRouteImport } from './routes/threats'
import { Route as TelemetryRouteImport } from './routes/telemetry'
import { Route as MaritimeRouteImport } from './routes/maritime'
import { Route as LiveMapRouteImport } from './routes/live-map'
import { Route as GroundRouteImport } from './routes/ground'
import { Route as AirFleetRouteImport } from './routes/air-fleet'
import { Route as AiCopilotRouteImport } from './routes/ai-copilot'
import { Route as IndexRouteImport } from './routes/index'

const ThreatsRoute = ThreatsRouteImport.update({
  id: '/threats',
  path: '/threats',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemetryRoute = TelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const MaritimeRoute = MaritimeRouteImport.update({
  id: '/maritime',
  path: '/maritime',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMapRoute = LiveMapRouteImport.update({
  id: '/live-map',
  path: '/live-map',
  getParentRoute: () => rootRouteImport,
} as any)
const GroundRoute = GroundRouteImport.update({
  id: '/ground',
  path: '/ground',
  getParentRoute: () => rootRouteImport,
} as any)
const AirFleetRoute = AirFleetRouteImport.update({
  id: '/air-fleet',
  path: '/air-fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCopilotRoute = AiCopilotRouteImport.update({
  id: '/ai-copilot',
  path: '/ai-copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-copilot': typeof AiCopilotRoute
  '/air-fleet': typeof AirFleetRoute
  '/ground': typeof GroundRoute
  '/live-map': typeof LiveMapRoute
  '/maritime': typeof MaritimeRoute
  '/telemetry': typeof TelemetryRoute
  '/threats': typeof ThreatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-copilot': typeof AiCopilotRoute
  '/air-fleet': typeof AirFleetRoute
  '/ground': typeof GroundRoute
  '/live-map': typeof LiveMapRoute
  '/maritime': typeof MaritimeRoute
  '/telemetry': typeof TelemetryRoute
  '/threats': typeof ThreatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-copilot': typeof AiCopilotRoute
  '/air-fleet': typeof AirFleetRoute
  '/ground': typeof GroundRoute
  '/live-map': typeof LiveMapRoute
  '/maritime': typeof MaritimeRoute
  '/telemetry': typeof TelemetryRoute
  '/threats': typeof ThreatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-copilot'
    | '/air-fleet'
    | '/ground'
    | '/live-map'
    | '/maritime'
    | '/telemetry'
    | '/threats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-copilot'
    | '/air-fleet'
    | '/ground'
    | '/live-map'
    | '/maritime'
    | '/telemetry'
    | '/threats'
  id:
    | '__root__'
    | '/'
    | '/ai-copilot'
    | '/air-fleet'
    | '/ground'
    | '/live-map'
    | '/maritime'
    | '/telemetry'
    | '/threats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiCopilotRoute: typeof AiCopilotRoute
  AirFleetRoute: typeof AirFleetRoute
  GroundRoute: typeof GroundRoute
  LiveMapRoute: typeof LiveMapRoute
  MaritimeRoute: typeof MaritimeRoute
  TelemetryRoute: typeof TelemetryRoute
  ThreatsRoute: typeof ThreatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/threats': {
      id: '/threats'
      path: '/threats'
      fullPath: '/threats'
      preLoaderRoute: typeof ThreatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemetry': {
      id: '/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maritime': {
      id: '/maritime'
      path: '/maritime'
      fullPath: '/maritime'
      preLoaderRoute: typeof MaritimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-map': {
      id: '/live-map'
      path: '/live-map'
      fullPath: '/live-map'
      preLoaderRoute: typeof LiveMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ground': {
      id: '/ground'
      path: '/ground'
      fullPath: '/ground'
      preLoaderRoute: typeof GroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/air-fleet': {
      id: '/air-fleet'
      path: '/air-fleet'
      fullPath: '/air-fleet'
      preLoaderRoute: typeof AirFleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-copilot': {
      id: '/ai-copilot'
      path: '/ai-copilot'
      fullPath: '/ai-copilot'
      preLoaderRoute: typeof AiCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiCopilotRoute: AiCopilotRoute,
  AirFleetRoute: AirFleetRoute,
  GroundRoute: GroundRoute,
  LiveMapRoute: LiveMapRoute,
  MaritimeRoute: MaritimeRoute,
  TelemetryRoute: TelemetryRoute,
  ThreatsRoute: ThreatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
